In [1]:
import numpy as np

In [2]:
print("hello world")

hello world


In [3]:
myarr=np.array([3,6,32,7]) 

In [4]:
myarr

array([ 3,  6, 32,  7])

In [5]:
myarr=np.array([3,6,32,7],np.int8) # define int 8 :  the mameroy management is in your hand

In [6]:
myarr

array([ 3,  6, 32,  7], dtype=int8)

In [7]:
myarr[0]

3

In [8]:
myarr.shape

(4,)

In [9]:
myarr1=np.array([[2,3,4],[1,2,3]])

In [10]:
myarr1.shape

(2, 3)

In [11]:
myarr1.dtype 

dtype('int64')

In [12]:
myarr1[0,1]=32 # changing the value in arry

In [13]:
myarr1

array([[ 2, 32,  4],
       [ 1,  2,  3]])

In [14]:
#There are 5 general mechanisms for creating arrays:

#Conversion from other Python structures (e.g., lists, tuples)
#Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
#Reading arrays from disk, either from standard or custom formats
#Creating arrays from raw bytes through the use of strings or buffers
#Use of special library functions (e.g., random)

In [15]:
#list se numpy array

In [16]:
listarray = np.array([[1,2,3],[5,8,5],[0,3,1]])

In [17]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [18]:
listarray.dtype

dtype('int64')

In [19]:
listarray.shape

(3, 3)

In [20]:
listarray.size

9

In [21]:
#Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)

In [22]:
zeros=np.zeros((2,5))

In [23]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
zeros.shape

(2, 5)

In [25]:
zeros.size

10

In [26]:
rng=np.arange(15) #range

In [27]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
lspace=np.linspace(1,50,10) #equally spaced values : 10 space between 1 to 50

In [29]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [30]:
lspace1=np.linspace(1,2,10)

In [31]:
lspace1

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [32]:
emp=np.empty((4,6)) #it gives (4,6) matrix with random values

In [33]:
emp

array([[1.72723371e-077, 1.72723371e-077, 5.92878775e-323,
        6.93397097e-310, 4.94065646e-324, 0.00000000e+000],
       [0.00000000e+000, 4.04738577e-320, 0.00000000e+000,
        1.23022346e-321, 6.93397153e-310, 9.88131292e-324],
       [            nan, 0.00000000e+000, 6.93397154e-310,
        3.06320700e-322, 1.72723371e-077, 2.32035230e+077],
       [1.97626258e-323, 0.00000000e+000, 0.00000000e+000,
        4.94065646e-324,             nan, 1.66880539e-308]])

In [34]:
emp_like=np.empty_like(lspace) #empty array copy the other array

In [35]:
emp_like

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

In [36]:
ide=np.identity(45) #identity keyword returns identity matrix 

In [37]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [38]:
ide.shape

(45, 45)

In [39]:
arr3=np.arange(99)

In [40]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [41]:
arr3.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [42]:
arr3.ravel() #ravel makes an 1D array 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr3.shape

(99,)

In [44]:
# axis=0 north to south , axis=1 Left to right

In [45]:
x=[[1,2,3,],[4,5,6],[7,1,0]]

In [46]:
ar=np.array(x)

In [47]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
ar.sum(axis=0)

array([12,  8,  9])

In [49]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [50]:
ar.sum()

29

In [51]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [52]:
ar.flat

In [53]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [54]:
ar.ndim # number of direction

2

In [55]:
ar.size

9

In [56]:
ar.nbytes #tota; bytes consume

72

In [57]:
one = np.array([1,2,3,4,5])

In [58]:
one.argmax() #it gives index of maximum value. here 5 is max so its index number is 4...start from 0

4

In [59]:
one.argmin() #it gives index of minimum value. here 1 is min so its index number is 0...start from 0

0

In [60]:
one.argsort() #gives sorted index value.(it does not return values)

array([0, 1, 2, 3, 4])

In [61]:
ar.argmin()

8

In [62]:
ar.argmax()

6

In [63]:
ar.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [64]:
ar.argmax(axis=0)

array([2, 1, 1])

In [65]:
ar.argmax(axis=1)

array([2, 2, 0])

In [66]:
ar2=np.array([[1,2,3],[4,0,8],[8,1,0]])

In [67]:
ar + ar2

array([[ 2,  4,  6],
       [ 8,  5, 14],
       [15,  2,  0]])

In [68]:
[3,2,4]+[1,2,3]

[3, 2, 4, 1, 2, 3]

In [69]:
ar*ar2 #eliment vise multiplication

array([[ 1,  4,  9],
       [16,  0, 48],
       [56,  1,  0]])

In [70]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [71]:
np.sqrt(ar2)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 0.        , 2.82842712],
       [2.82842712, 1.        , 0.        ]])

In [72]:
ar.sum()

29

In [73]:
ar.min()

0

In [74]:
ar.max()

7

In [75]:
np.where(ar>5) #where is the value greater than 5

(array([1, 2]), array([2, 0]))

In [76]:
type(np.where(ar>5))

tuple

In [77]:
np.count_nonzero(ar)

8

In [78]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1]))

In [79]:
ar[1,2]=0

In [80]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2]), array([0, 1, 2, 0, 1, 0, 1]))

In [81]:
import sys

In [82]:
py_ar = [0,4,55,2]

In [83]:
np_ar = np.array(py_ar)

In [84]:
sys.getsizeof(1)*len(py_ar)

112

In [85]:
np_ar.itemsize * np_ar.size

32