In [1]:
import numpy as np

In [2]:
l1=([1,2,3,4])

In [3]:
n1=np.array(l1) #1D array

In [4]:
n1

array([1, 2, 3, 4])

In [5]:
type(n1)

numpy.ndarray

In [6]:
l2=([[1,2,3],[3,4,4]]) #2-D array

In [7]:
n2=np.array(l2)

In [8]:
n2

array([[1, 2, 3],
       [3, 4, 4]])

In [9]:
type(n2)

numpy.ndarray

In [10]:
n3=np.zeros((2,3))

In [11]:
n3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
type(n3)

numpy.ndarray

In [13]:
n4=np.full((3,3),10) #assign 10 value in the maxtrix

In [14]:
n4

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [15]:
n5=np.arange(10,20)

In [16]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
n6=np.arange(10,20,1)

In [18]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
n6=np.arange(10,20,0.5)

In [20]:
n6

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [21]:
np.random.randint(100,200,40) #getting random numbers

array([131, 157, 159, 104, 191, 102, 175, 119, 165, 144, 195, 170, 190,
       155, 136, 122, 121, 191, 158, 102, 177, 103, 187, 179, 194, 122,
       161, 120, 151, 142, 104, 158, 146, 161, 105, 155, 170, 131, 164,
       109])

In [22]:
n4.shape

(3, 3)

In [23]:
n3.shape

(2, 3)

In [24]:
np.vstack((n3,n4)) #verticle stack

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [25]:
np.hstack((n5,n6)) #horizontal stack

array([10. , 11. , 12. , 13. , 14. , 15. , 16. , 17. , 18. , 19. , 10. ,
       10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [26]:
a1=np.array([10,20,30,40,50,60,70,80])
a2=np.array([40,50,60,70,90,100])

In [27]:
np.intersect1d(a1,a2) # common values

array([40, 50, 60, 70])

In [28]:
np.setdiff1d(a1,a2) # a1-a2 = means unique values of a1

array([10, 20, 30, 80])

In [29]:
np.setdiff1d(a2,a1) # a2-a1 = means unique values of a2

array([ 90, 100])

In [32]:
np.mean(n6)

14.75

In [37]:
np.median(n1)

2.5

In [35]:
np.std(n6)

2.883140648667699